window.AJS_SEARCH_INDEX = [
  {
    "lang": "da",
    "type": "species",
    "title": "Ackie varan",
    "latin": "Varanus acanthurus",
    "group": "Skinker og store øgler",
    "habitat": "Desert and arid habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "skinker og store øgler",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/ackie-monitor.html",
    "description": "Praktisk guide til Ackie varan: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Ackie monitor",
    "latin": "Varanus acanthurus",
    "group": "Skinks and large lizards",
    "habitat": "Desert and arid habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "skinks and large lizards",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/ackie-monitor.html",
    "description": "Practical guide for Ackie monitor: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Afrikansk fedthalekgekko",
    "latin": "Hemitheconyx caudicinctus",
    "group": "Gekkoer",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/african-fat-tailed-gecko.html",
    "description": "Praktisk guide til Afrikansk fedthalekgekko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "African fat-tailed gecko",
    "latin": "Hemitheconyx caudicinctus",
    "group": "Geckos",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/african-fat-tailed-gecko.html",
    "description": "Practical guide for African fat-tailed gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Argentine black-and-white tegu",
    "latin": "Salvator merianae",
    "group": "Skinker og store øgler",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Very experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "skinker og store øgler",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/argentine-tegu.html",
    "description": "Praktisk guide til Argentine black-and-white tegu: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Argentine black and white tegu",
    "latin": "Salvator merianae",
    "group": "Skinks and large lizards",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Advanced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "skinks and large lizards",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/argentine-tegu.html",
    "description": "Practical guide for Argentine black and white tegu: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Ball python",
    "latin": "Python regius",
    "group": "Pythoner",
    "habitat": "Slanger",
    "difficulty": "Beginner+",
    "activity": "Nat-/skumringsaktiv",
    "keywords": [
      "art",
      "reptil",
      "pythoner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/ball-python.html",
    "description": "Praktisk guide til Ball python: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Ball python",
    "latin": "Python regius",
    "group": "Pythons",
    "habitat": "Snakes",
    "difficulty": "Beginner+",
    "activity": "Nocturnal/crepuscular",
    "keywords": [
      "species",
      "reptile",
      "pythons",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/ball-python.html",
    "description": "Practical guide for Ball python: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Bearded dragon",
    "latin": "Pogona vitticeps",
    "group": "Agamer",
    "habitat": "Desert and arid habitats",
    "difficulty": "Beginner+",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "agamer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/bearded-dragon.html",
    "description": "Praktisk guide til Bearded dragon: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Bearded dragon",
    "latin": "Pogona vitticeps",
    "group": "Agamids",
    "habitat": "Desert and arid habitats",
    "difficulty": "Beginner+",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "agamids",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/bearded-dragon.html",
    "description": "Practical guide for Bearded dragon: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Blue-tongued skink",
    "latin": "Tiliqua scincoides / Tiliqua spp.",
    "group": "Skinker og store øgler",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Beginner+",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "skinker og store øgler",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/blue-tongued-skink.html",
    "description": "Praktisk guide til Blue-tongued skink: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Blue-tongued skink",
    "latin": "Tiliqua scincoides / Tiliqua spp.",
    "group": "Skinks and large lizards",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Beginner+",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "skinks and large lizards",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/blue-tongued-skink.html",
    "description": "Practical guide for Blue-tongued skink: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Boa constrictor",
    "latin": "Boa constrictor / Boa imperator",
    "group": "Boaer",
    "habitat": "Slanger",
    "difficulty": "Experienced",
    "activity": "Nat-/skumringsaktiv",
    "keywords": [
      "art",
      "reptil",
      "boaer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/boa-constrictor.html",
    "description": "Praktisk guide til Boa constrictor: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Boa constrictor",
    "latin": "Boa constrictor / Boa imperator",
    "group": "Boas",
    "habitat": "Snakes",
    "difficulty": "Experienced",
    "activity": "Nocturnal/crepuscular",
    "keywords": [
      "species",
      "reptile",
      "boas",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/boa-constrictor.html",
    "description": "Practical guide for Boa constrictor: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "California kingsnake",
    "latin": "Lampropeltis californiae",
    "group": "Snoge",
    "habitat": "Slanger",
    "difficulty": "Beginner+",
    "activity": "Crepuscular",
    "keywords": [
      "art",
      "reptil",
      "snoge",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/california-kingsnake.html",
    "description": "Praktisk guide til California kingsnake: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "California kingsnake",
    "latin": "Lampropeltis californiae",
    "group": "Colubrids",
    "habitat": "Snakes",
    "difficulty": "Beginner+",
    "activity": "Crepuscular",
    "keywords": [
      "species",
      "reptile",
      "colubrids",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/california-kingsnake.html",
    "description": "Practical guide for California kingsnake: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Tæppepython",
    "latin": "Morelia spilota",
    "group": "Pythoner",
    "habitat": "Slanger",
    "difficulty": "Experienced",
    "activity": "Skumrings-/nataktiv",
    "keywords": [
      "art",
      "reptil",
      "pythoner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/carpet-python.html",
    "description": "Praktisk guide til Tæppepython: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Carpet python",
    "latin": "Morelia spilota",
    "group": "Pythons",
    "habitat": "Snakes",
    "difficulty": "Experienced",
    "activity": "Crepuscular/nocturnal",
    "keywords": [
      "species",
      "reptile",
      "pythons",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/carpet-python.html",
    "description": "Practical guide for Carpet python: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Børnepython",
    "latin": "Antaresia childreni",
    "group": "Pythoner",
    "habitat": "Slanger",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "art",
      "reptil",
      "pythoner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/childrens-python.html",
    "description": "Praktisk guide til Børnepython: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Children’s python",
    "latin": "Antaresia childreni",
    "group": "Pythons",
    "habitat": "Snakes",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "species",
      "reptile",
      "pythons",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/childrens-python.html",
    "description": "Practical guide for Children’s python: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Kinesisk hulegekko",
    "latin": "Goniurosaurus hainanensis",
    "group": "Gekkoer",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Experienced",
    "activity": "Nocturnal",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/chinese-cave-gecko.html",
    "description": "Praktisk guide til Kinesisk hulegekko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Chinese cave gecko",
    "latin": "Goniurosaurus hainanensis",
    "group": "Geckos",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Experienced",
    "activity": "Nocturnal",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/chinese-cave-gecko.html",
    "description": "Practical guide for Chinese cave gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Reeves’ turtle",
    "latin": "Mauremys reevesii",
    "group": "Waterskildpadder",
    "habitat": "Akvatisk / semi-akvatisk",
    "difficulty": "Beginner+",
    "activity": "Akvatisk/dagaktiv",
    "keywords": [
      "art",
      "reptil",
      "vandskildpadder",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/chinese-reeves-turtle.html",
    "description": "Praktisk guide til Reeves’ turtle: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Reeves’ turtle",
    "latin": "Mauremys reevesii",
    "group": "Aquatic turtles",
    "habitat": "Aquatic / semi-aquatic",
    "difficulty": "Beginner+",
    "activity": "Aquatic/diurnal",
    "keywords": [
      "species",
      "reptile",
      "aquatic turtles",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/chinese-reeves-turtle.html",
    "description": "Practical guide for Reeves’ turtle: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Corn snake",
    "latin": "Pantherophis guttatus",
    "group": "Snoge",
    "habitat": "Slanger",
    "difficulty": "Beginner",
    "activity": "Crepuscular",
    "keywords": [
      "art",
      "reptil",
      "snoge",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/corn-snake.html",
    "description": "Praktisk guide til Corn snake: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Corn snake",
    "latin": "Pantherophis guttatus",
    "group": "Colubrids",
    "habitat": "Snakes",
    "difficulty": "Beginner",
    "activity": "Crepuscular",
    "keywords": [
      "species",
      "reptile",
      "colubrids",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/corn-snake.html",
    "description": "Practical guide for Corn snake: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Crested gecko",
    "latin": "Correlophus ciliatus",
    "group": "Gekkoer",
    "habitat": "Tropiske habitater",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/crested-gecko.html",
    "description": "Praktisk guide til Crested gecko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Crested gecko",
    "latin": "Correlophus ciliatus",
    "group": "Geckos",
    "habitat": "Tropical habitats",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/crested-gecko.html",
    "description": "Practical guide for Crested gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Gargoyle gecko",
    "latin": "Rhacodactylus auriculatus",
    "group": "Gekkoer",
    "habitat": "Tropiske habitater",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/gargoyle-gecko.html",
    "description": "Praktisk guide til Gargoyle gecko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Gargoyle gecko",
    "latin": "Rhacodactylus auriculatus",
    "group": "Geckos",
    "habitat": "Tropical habitats",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/gargoyle-gecko.html",
    "description": "Practical guide for Gargoyle gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Garter snake",
    "latin": "Thamnophis spp.",
    "group": "Snoge",
    "habitat": "Slanger",
    "difficulty": "Beginner+",
    "activity": "Dag-/skumringsaktiv",
    "keywords": [
      "art",
      "reptil",
      "snoge",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/garter-snake.html",
    "description": "Praktisk guide til Garter snake: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Garter snake",
    "latin": "Thamnophis spp.",
    "group": "Colubrids",
    "habitat": "Snakes",
    "difficulty": "Beginner+",
    "activity": "Diurnal/crepuscular",
    "keywords": [
      "species",
      "reptile",
      "colubrids",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/garter-snake.html",
    "description": "Practical guide for Garter snake: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Greek tortoise",
    "latin": "Testudo hermanni / Testudo graeca complex",
    "group": "Landskildpadder",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "landskildpadder",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/greek-tortoise.html",
    "description": "Praktisk guide til Greek tortoise: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Greek/Hermann’s tortoise",
    "latin": "Testudo hermanni / Testudo graeca complex",
    "group": "Tortoises",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "tortoises",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/greek-tortoise.html",
    "description": "Practical guide for Greek/Hermann’s tortoise: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Green iguana",
    "latin": "Iguana iguana",
    "group": "Leguaner",
    "habitat": "Tropiske habitater",
    "difficulty": "Very experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "leguaner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/green-iguana.html",
    "description": "Praktisk guide til Green iguana: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Green iguana",
    "latin": "Iguana iguana",
    "group": "Iguanas",
    "habitat": "Tropical habitats",
    "difficulty": "Advanced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "iguanas",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/green-iguana.html",
    "description": "Practical guide for Green iguana: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Grøn træpython",
    "latin": "Morelia viridis",
    "group": "Pythoner",
    "habitat": "Slanger",
    "difficulty": "Very experienced",
    "activity": "Nocturnal/arboreal",
    "keywords": [
      "art",
      "reptil",
      "pythoner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/green-tree-python.html",
    "description": "Praktisk guide til Grøn træpython: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Green tree python",
    "latin": "Morelia viridis",
    "group": "Pythons",
    "habitat": "Snakes",
    "difficulty": "Advanced",
    "activity": "Nocturnal/arboreal",
    "keywords": [
      "species",
      "reptile",
      "pythons",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/green-tree-python.html",
    "description": "Practical guide for Green tree python: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Hognose snake",
    "latin": "Heterodon nasicus",
    "group": "Snoge",
    "habitat": "Slanger",
    "difficulty": "Beginner+",
    "activity": "Dag-/skumringsaktiv",
    "keywords": [
      "art",
      "reptil",
      "snoge",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/hognose-snake.html",
    "description": "Praktisk guide til Hognose snake: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Hognose snake",
    "latin": "Heterodon nasicus",
    "group": "Colubrids",
    "habitat": "Snakes",
    "difficulty": "Beginner+",
    "activity": "Diurnal/crepuscular",
    "keywords": [
      "species",
      "reptile",
      "colubrids",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/hognose-snake.html",
    "description": "Practical guide for Hognose snake: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Jacksons kamæleon",
    "latin": "Trioceros jacksonii",
    "group": "Kamæleoner",
    "habitat": "Tropiske habitater",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "kamæleoner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/jacksons-chameleon.html",
    "description": "Praktisk guide til Jacksons kamæleon: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Jackson’s chameleon",
    "latin": "Trioceros jacksonii",
    "group": "Chameleons",
    "habitat": "Tropical habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "chameleons",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/jacksons-chameleon.html",
    "description": "Practical guide for Jackson’s chameleon: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Kenyan sand boa",
    "latin": "Gongylophis colubrinus",
    "group": "Boaer",
    "habitat": "Desert and arid habitats",
    "difficulty": "Beginner+",
    "activity": "Gravende/nataktiv",
    "keywords": [
      "art",
      "reptil",
      "boaer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/kenyan-sand-boa.html",
    "description": "Praktisk guide til Kenyan sand boa: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Kenyan sand boa",
    "latin": "Gongylophis colubrinus",
    "group": "Boas",
    "habitat": "Desert and arid habitats",
    "difficulty": "Beginner+",
    "activity": "Enclosurerowing/nocturnal",
    "keywords": [
      "species",
      "reptile",
      "boas",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/kenyan-sand-boa.html",
    "description": "Practical guide for Kenyan sand boa: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Leopard gecko",
    "latin": "Eublepharis macularius",
    "group": "Gekkoer",
    "habitat": "Desert and arid habitats",
    "difficulty": "Beginner",
    "activity": "Nocturnal/skumringsaktiv",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/leopard-gecko.html",
    "description": "Praktisk guide til Leopard gecko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Leopard gecko",
    "latin": "Eublepharis macularius",
    "group": "Geckos",
    "habitat": "Desert and arid habitats",
    "difficulty": "Beginner",
    "activity": "Nocturnal/crepuscular",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/leopard-gecko.html",
    "description": "Practical guide for Leopard gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Leopard tortoise",
    "latin": "Stigmochelys pardalis",
    "group": "Landskildpadder",
    "habitat": "Desert and arid habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "landskildpadder",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/leopard-tortoise.html",
    "description": "Praktisk guide til Leopard tortoise: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Leopard tortoise",
    "latin": "Stigmochelys pardalis",
    "group": "Tortoises",
    "habitat": "Desert and arid habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "tortoises",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/leopard-tortoise.html",
    "description": "Practical guide for Leopard tortoise: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Madagaskar daggekko",
    "latin": "Phelsuma grandis",
    "group": "Gekkoer",
    "habitat": "Tropiske habitater",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/madagascar-day-gecko.html",
    "description": "Praktisk guide til Madagaskar daggekko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Madagascar giant day gecko",
    "latin": "Phelsuma grandis",
    "group": "Geckos",
    "habitat": "Tropical habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/madagascar-day-gecko.html",
    "description": "Practical guide for Madagascar giant day gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Milk snake",
    "latin": "Lampropeltis triangulum",
    "group": "Snoge",
    "habitat": "Slanger",
    "difficulty": "Beginner+",
    "activity": "Crepuscular",
    "keywords": [
      "art",
      "reptil",
      "snoge",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/milk-snake.html",
    "description": "Praktisk guide til Milk snake: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Milk snake",
    "latin": "Lampropeltis triangulum",
    "group": "Colubrids",
    "habitat": "Snakes",
    "difficulty": "Beginner+",
    "activity": "Crepuscular",
    "keywords": [
      "species",
      "reptile",
      "colubrids",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/milk-snake.html",
    "description": "Practical guide for Milk snake: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Mourning gecko",
    "latin": "Lepidodactylus lugubris",
    "group": "Gekkoer",
    "habitat": "Tropiske habitater",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/mourning-gecko.html",
    "description": "Praktisk guide til Mourning gecko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Mourning gecko",
    "latin": "Lepidodactylus lugubris",
    "group": "Geckos",
    "habitat": "Tropical habitats",
    "difficulty": "Beginner+",
    "activity": "Nocturnal",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/mourning-gecko.html",
    "description": "Practical guide for Mourning gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Common musk turtle",
    "latin": "Sternotherus odoratus",
    "group": "Waterskildpadder",
    "habitat": "Akvatisk / semi-akvatisk",
    "difficulty": "Beginner+",
    "activity": "Akvatisk/skumringsaktiv",
    "keywords": [
      "art",
      "reptil",
      "vandskildpadder",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/musk-turtle.html",
    "description": "Praktisk guide til Common musk turtle: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Common musk turtle",
    "latin": "Sternotherus odoratus",
    "group": "Aquatic turtles",
    "habitat": "Aquatic / semi-aquatic",
    "difficulty": "Beginner+",
    "activity": "Aquatic/crepuscular",
    "keywords": [
      "species",
      "reptile",
      "aquatic turtles",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/musk-turtle.html",
    "description": "Practical guide for Common musk turtle: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Panther chameleon",
    "latin": "Furcifer pardalis",
    "group": "Kamæleoner",
    "habitat": "Tropiske habitater",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "kamæleoner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/panther-chameleon.html",
    "description": "Praktisk guide til Panther chameleon: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Panther chameleon",
    "latin": "Furcifer pardalis",
    "group": "Chameleons",
    "habitat": "Tropical habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "chameleons",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/panther-chameleon.html",
    "description": "Practical guide for Panther chameleon: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Red-eared slider",
    "latin": "Trachemys scripta elegans",
    "group": "Waterskildpadder",
    "habitat": "Akvatisk / semi-akvatisk",
    "difficulty": "Experienced",
    "activity": "Diurnal/akvatisk",
    "keywords": [
      "art",
      "reptil",
      "vandskildpadder",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/red-eared-slider.html",
    "description": "Praktisk guide til Red-eared slider: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Red-eared slider",
    "latin": "Trachemys scripta elegans",
    "group": "Aquatic turtles",
    "habitat": "Aquatic / semi-aquatic",
    "difficulty": "Experienced",
    "activity": "Diurnal/aquatic",
    "keywords": [
      "species",
      "reptile",
      "aquatic turtles",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/red-eared-slider.html",
    "description": "Practical guide for Red-eared slider: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Rosy boa",
    "latin": "Lichanura trivirgata",
    "group": "Boaer",
    "habitat": "Slanger",
    "difficulty": "Beginner+",
    "activity": "Nat-/skumringsaktiv",
    "keywords": [
      "art",
      "reptil",
      "boaer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/rosy-boa.html",
    "description": "Praktisk guide til Rosy boa: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Rosy boa",
    "latin": "Lichanura trivirgata",
    "group": "Boas",
    "habitat": "Snakes",
    "difficulty": "Beginner+",
    "activity": "Nocturnal/crepuscular",
    "keywords": [
      "species",
      "reptile",
      "boas",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/rosy-boa.html",
    "description": "Practical guide for Rosy boa: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Russian tortoise",
    "latin": "Testudo horsfieldii",
    "group": "Landskildpadder",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "landskildpadder",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/russian-tortoise.html",
    "description": "Praktisk guide til Russian tortoise: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Russian tortoise",
    "latin": "Testudo horsfieldii",
    "group": "Tortoises",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "tortoises",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/russian-tortoise.html",
    "description": "Practical guide for Russian tortoise: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Savannah varan",
    "latin": "Varanus exanthematicus",
    "group": "Skinker og store øgler",
    "habitat": "Desert and arid habitats",
    "difficulty": "Very experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "skinker og store øgler",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/savannah-monitor.html",
    "description": "Praktisk guide til Savannah varan: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Savannah monitor",
    "latin": "Varanus exanthematicus",
    "group": "Skinks and large lizards",
    "habitat": "Desert and arid habitats",
    "difficulty": "Advanced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "skinks and large lizards",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/savannah-monitor.html",
    "description": "Practical guide for Savannah monitor: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Sulcata landskildpadde",
    "latin": "Centrochelys sulcata",
    "group": "Landskildpadder",
    "habitat": "Desert and arid habitats",
    "difficulty": "Very experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "landskildpadder",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/sulcata-tortoise.html",
    "description": "Praktisk guide til Sulcata landskildpadde: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Sulcata tortoise",
    "latin": "Centrochelys sulcata",
    "group": "Tortoises",
    "habitat": "Desert and arid habitats",
    "difficulty": "Advanced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "tortoises",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/sulcata-tortoise.html",
    "description": "Practical guide for Sulcata tortoise: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Tokay gekko",
    "latin": "Gekko gecko",
    "group": "Gekkoer",
    "habitat": "Tropiske habitater",
    "difficulty": "Experienced",
    "activity": "Nocturnal",
    "keywords": [
      "art",
      "reptil",
      "gekkoer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/tokay-gecko.html",
    "description": "Praktisk guide til Tokay gekko: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Tokay gecko",
    "latin": "Gekko gecko",
    "group": "Geckos",
    "habitat": "Tropical habitats",
    "difficulty": "Experienced",
    "activity": "Nocturnal",
    "keywords": [
      "species",
      "reptile",
      "geckos",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/tokay-gecko.html",
    "description": "Practical guide for Tokay gecko: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Uromastyx",
    "latin": "Uromastyx spp.",
    "group": "Agamer",
    "habitat": "Desert and arid habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "agamer",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/uromastyx.html",
    "description": "Praktisk guide til Uromastyx: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Uromastyx",
    "latin": "Uromastyx spp.",
    "group": "Agamids",
    "habitat": "Desert and arid habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "agamids",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/uromastyx.html",
    "description": "Practical guide for Uromastyx: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "species",
    "title": "Veiled chameleon",
    "latin": "Chamaeleo calyptratus",
    "group": "Kamæleoner",
    "habitat": "Tropiske habitater",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "art",
      "reptil",
      "kamæleoner",
      "varme",
      "uvb",
      "fugt",
      "foder",
      "vitaminer",
      "vinterdvale",
      "bur",
      "terrarie"
    ],
    "url": "/species/veiled-chameleon.html",
    "description": "Praktisk guide til Veiled chameleon: mindstemål, varme dag/nat, UVB, fugt, foder, vitaminer, avl og vinterdvale."
  },
  {
    "lang": "en",
    "type": "species",
    "title": "Veiled chameleon",
    "latin": "Chamaeleo calyptratus",
    "group": "Chameleons",
    "habitat": "Tropical habitats",
    "difficulty": "Experienced",
    "activity": "Diurnal",
    "keywords": [
      "species",
      "reptile",
      "chameleons",
      "heat",
      "uvb",
      "humidity",
      "food",
      "vitamins",
      "brumation",
      "enclosure",
      "terrarium"
    ],
    "url": "/en/species/veiled-chameleon.html",
    "description": "Practical guide for Veiled chameleon: minimum enclosure, day/night heat, UVB, humidity, feeding, supplements, breeding and brumation."
  },
  {
    "lang": "da",
    "type": "habitat",
    "title": "Desert and arid habitats",
    "latin": "",
    "group": "Habitater",
    "habitat": "Desert and arid habitats",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarie",
      "inspiration",
      "miljø"
    ],
    "url": "/habitats/desert.html",
    "description": "Habitatguide og relevante arter."
  },
  {
    "lang": "da",
    "type": "habitat",
    "title": "Tropiske habitater",
    "latin": "",
    "group": "Habitater",
    "habitat": "Tropiske habitater",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarie",
      "inspiration",
      "miljø"
    ],
    "url": "/habitats/tropical.html",
    "description": "Habitatguide og relevante arter."
  },
  {
    "lang": "da",
    "type": "habitat",
    "title": "Forest, Mediterranean and terrestrial species",
    "latin": "",
    "group": "Habitater",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarie",
      "inspiration",
      "miljø"
    ],
    "url": "/habitats/forest.html",
    "description": "Habitatguide og relevante arter."
  },
  {
    "lang": "da",
    "type": "habitat",
    "title": "Slanger",
    "latin": "",
    "group": "Habitater",
    "habitat": "Slanger",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarie",
      "inspiration",
      "miljø"
    ],
    "url": "/habitats/snake.html",
    "description": "Habitatguide og relevante arter."
  },
  {
    "lang": "da",
    "type": "habitat",
    "title": "Waterskildpadder og semi-akvatiske arter",
    "latin": "",
    "group": "Habitater",
    "habitat": "Waterskildpadder og semi-akvatiske arter",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarie",
      "inspiration",
      "miljø"
    ],
    "url": "/habitats/aquatic.html",
    "description": "Habitatguide og relevante arter."
  },
  {
    "lang": "da",
    "type": "habitat",
    "title": "Beginnervenlige arter",
    "latin": "",
    "group": "Habitater",
    "habitat": "Beginnervenlige arter",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarie",
      "inspiration",
      "miljø"
    ],
    "url": "/habitats/beginner.html",
    "description": "Habitatguide og relevante arter."
  },
  {
    "lang": "en",
    "type": "habitat",
    "title": "Desert and arid habitats",
    "latin": "",
    "group": "Habitats",
    "habitat": "Desert and arid habitats",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarium",
      "inspiration",
      "environment"
    ],
    "url": "/en/habitats/desert.html",
    "description": "Habitat guide and related species."
  },
  {
    "lang": "en",
    "type": "habitat",
    "title": "Tropical habitats",
    "latin": "",
    "group": "Habitats",
    "habitat": "Tropical habitats",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarium",
      "inspiration",
      "environment"
    ],
    "url": "/en/habitats/tropical.html",
    "description": "Habitat guide and related species."
  },
  {
    "lang": "en",
    "type": "habitat",
    "title": "Forest, Mediterranean and terrestrial species",
    "latin": "",
    "group": "Habitats",
    "habitat": "Forest, Mediterranean and terrestrial species",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarium",
      "inspiration",
      "environment"
    ],
    "url": "/en/habitats/forest.html",
    "description": "Habitat guide and related species."
  },
  {
    "lang": "en",
    "type": "habitat",
    "title": "Snakes",
    "latin": "",
    "group": "Habitats",
    "habitat": "Snakes",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarium",
      "inspiration",
      "environment"
    ],
    "url": "/en/habitats/snake.html",
    "description": "Habitat guide and related species."
  },
  {
    "lang": "en",
    "type": "habitat",
    "title": "Aquatic and semi-aquatic turtles",
    "latin": "",
    "group": "Habitats",
    "habitat": "Aquatic and semi-aquatic turtles",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarium",
      "inspiration",
      "environment"
    ],
    "url": "/en/habitats/aquatic.html",
    "description": "Habitat guide and related species."
  },
  {
    "lang": "en",
    "type": "habitat",
    "title": "Beginner-friendly species",
    "latin": "",
    "group": "Habitats",
    "habitat": "Beginner-friendly species",
    "difficulty": "",
    "activity": "",
    "keywords": [
      "habitat",
      "terrarium",
      "inspiration",
      "environment"
    ],
    "url": "/en/habitats/beginner.html",
    "description": "Habitat guide and related species."
  }
];
